// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piubcrczwttjvcszkgkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpdWJjcmN6d3R0anZjc3prZ2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNzQ0OTAsImV4cCI6MjA1ODg1MDQ5MH0.x8IKw483FBdK0pETbC660nQz0N8sQRoK3NsShwwfpW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);